apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-react-gpt
spec:
  selector:
    matchLabels:
      app: ollama-react-gpt
  template:
    metadata:
      labels:
        app: ollama-react-gpt
    spec:
      containers:
      - name: ollama-react-gpt
        image: registry.digitalocean.com/ollama-react-gpt/my-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: VITE_API_URL
          value: "http://157.230.235.32:8000"
